-- CreateEnum
CREATE TYPE "PostStatus" AS ENUM ('INITIALIZED', 'DRAFT', 'PUBLISHED', 'ARCHIVED');

-- AlterTable
ALTER TABLE "Post" ADD COLUMN     "status" "PostStatus" NOT NULL DEFAULT 'INITIALIZED';
